### ISSUE TITLE
VLC not detected

### ISSUE THREAD

**Issue by ShouldBeTanuki** [kaboussi/Botflix#15]
the program cannot identify VLC
![image](https://user-images.githubusercontent.com/104937681/166812511-bc38d65f-f391-47c6-bad3-fa613800f464.png)

**Comment by eduardo-rdgz** [comment]
I think this is using the `webtorrent` player flag. Can you open vlc from your console? Try `vlc --version` and paste the output.

**Comment by redelka00** [comment]
Do you have flatpak version of vlc

**Comment by redelka00** [comment]
i noticed that the vlc is capital, try to change it?

**Comment by eduardo-rdgz** [comment]
did you run? `python3 main.py config "vlc"`

**Comment by redelka00** [comment]
> did you run? `python3 main.py config "vlc"`

this should work, I'll close this issue if no response after 24 hours
