### ISSUE TITLE
Insufficient arch documentation

### ISSUE THREAD

**Issue by Seme4eg** [kaboussi/Botflix#49]
Installed `botflix-git` via yay. In readme its written 'set configuration first' - which configuration? i thought it means setting the default player, but the command given to do that failed. 
So i am stuck now on installation.

![image](https://github.com/kaboussi/Botflix/assets/24554850/1d96b58d-4c2f-4830-a401-3b1360473440)

**Comment by aurkaxi** [comment]
the command should be, `botflix config "mpv"`. 
`python3 main.py` is replaced with `botflix`

also i see you need rich library. try:
```bash
> source /usr/share/botflix/venv/bin/activate
> pip install rich
```

**Comment by kaboussi** [comment]
it should be clear now thanks to @aurkaxi #50
