### ISSUE TITLE
aur package doesn't install all needed python modules

### ISSUE THREAD

**Issue by Seme4eg** [kaboussi/Botflix#52]
installed botflix package from aur, when trying to run `botflix config"mpv"` i first get 'missing rich module', ok, installed aur python-rich, then trying to run same config command, get 'missing simple_term_menu' , installed python-simple-term-menu', now i get 'no module named scrapy'

Maybe something wrong with aur botflix package? i don't thiink it should be like that.

**Comment by aurkaxi** [comment]
Qfter you created #49 i updated the aur package. Did you re-install and still facing this issue?

**Comment by Seme4eg** [comment]
i didn't know you updated it, after reinstalling it doesn't miss any modules, but after running `botflix config"mpv"` i end up with a blank terminal screen with nothing on it. After ctrl-c i get following logs - http://0x0.st/HVbx.txt

**Comment by aurkaxi** [comment]
Can you connect to `https://www.torrentgalaxy.to/` from your browser? 
That sounds like a connectivity issue, some isp(s) block torrent sites. For me i stay for a while in that black screen but eventually i do get connected. 

However, no longer related to aur. 
@kaboussi

**Comment by Seme4eg** [comment]
yes, i can connect that site and also i don't see any network traffic appearing while im starnig at that blank screen.
i waited like 5 minutes, nothing happened.

**Comment by Seme4eg** [comment]
i can create another issue since that one is not related to aur
